podMonitors:
  - name: workspace
    matchLabels:
      component: workspace
      workspaceType: regular
    endpoints:
      - port: supervisor
        interval: 60s
        scrapeTimeout: 5s
        metricRelabelings:
          - sourceLabels:
              - '__name__'
            regex: gitpod_(.*)
            action: keep

serviceMonitors:
  - name: ws-manager
    services:
      selector:
        component: ws-manager
      ports:
        - name: metrics
          port: 9500
          targetPort: 9500
          protocol: TCP
    endpoints:
      - port: metrics
        interval: 30s
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

prometheus:
  enabled: true
